'use client';
import { useEffect, useState } from 'react';
import { Eye, EyeOff, UserRound, X } from 'lucide-react';
import { ProfileContext } from './profile-context';
import type { Session } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';
export default function AuthGate({children}:{children:React.ReactNode}) {
 const [profile,setProfile]=useState<{username:string;display_name:string|null}|null>(null);
 const [editingName,setEditingName]=useState('');
 const [profileOpen,setProfileOpen]=useState(false);
 const [profileMessage,setProfileMessage]=useState('');
 const [session,setSession]=useState<Session|null>(null);
 const [loading,setLoading]=useState(true);
 const [mode,setMode]=useState<'login'|'register'|'reset'>('login');
 const [email,setEmail]=useState('');
 const [password,setPassword]=useState('');
 const [username,setUsername]=useState('');
 const [message,setMessage]=useState('');
 const [busy,setBusy]=useState(false);
 const [showPassword,setShowPassword]=useState(false);
 useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active){setSession(data.session);setLoading(false)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{if(active){setSession(next);setLoading(false)}});return()=>{active=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!session){setProfile(null);return}let active=true;supabase.from('profiles').select('username,display_name').eq('id',session.user.id).single().then(({data})=>{if(active&&data){setProfile(data);setEditingName(data.display_name??'')}});return()=>{active=false}},[session?.user.id]);
 async function saveName(e:React.FormEvent){e.preventDefault();if(!session)return;const name=editingName.trim();if(name.length<3||name.length>80){setProfileMessage('Display name must be 3–80 characters.');return}const {error}=await supabase.from('profiles').update({display_name:name}).eq('id',session.user.id);if(error)setProfileMessage(error.message);else{setProfile(p=>p?{...p,display_name:name}:p);setProfileMessage('Display name saved.');}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');
  try {
   if(mode==='register'){if(username.trim().length<3||username.trim().length>80){setMessage('Display name must be 3–80 characters.');return}
    const {error}=await supabase.auth.signUp({email,password,options:{data:{display_name:username.trim()},emailRedirectTo:window.location.origin}});if(error)throw error;setMessage('Check your email for a verification link if this is a new account. Already registered? Sign in or reset your password.');}
   else if(mode==='reset'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(error)throw error;setMessage('If this address has an account, a reset email has been sent.');}
   else {const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}
  }catch(err){setMessage(err instanceof Error?err.message:'Something went wrong.')}finally{setBusy(false)}
 }
 if(loading)return <main className="grid min-h-screen place-items-center text-slate-300">Loading your workspace…</main>;
 if(session)return <ProfileContext.Provider value={{displayName:profile?.display_name||profile?.username||'My'}}><div className="fixed right-3 top-2 z-50 flex items-center gap-2 rounded-lg bg-slate-900/95 px-3 py-2 text-xs shadow"><button className="flex items-center gap-1 font-semibold text-slate-200 hover:text-teal-300" onClick={()=>setProfileOpen(true)} aria-label="Open profile settings"><UserRound size={15}/>{profile?.display_name||profile?.username||'Profile'}</button><button className="font-semibold text-teal-300" onClick={()=>supabase.auth.signOut()}>Sign out</button></div>{children}{profileOpen&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-4" onClick={()=>setProfileOpen(false)}><section role="dialog" aria-modal="true" aria-label="Profile settings" onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-2xl border border-white/10 bg-[#151e30] p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Profile settings</h2><button aria-label="Close profile" onClick={()=>setProfileOpen(false)}><X size={20}/></button></div><p className="mt-4 text-sm text-slate-400">Email</p><p className="mt-1 break-all font-medium">{session.user.email}</p><form onSubmit={saveName} className="mt-5"><label className="block text-sm text-slate-400">Display name<input required minLength={3} maxLength={80} value={editingName} onChange={e=>setEditingName(e.target.value)} placeholder="Your display name" className="mt-2 w-full rounded-lg bg-slate-800 p-3 text-white"/></label><button className="mt-4 rounded-lg bg-teal-400 px-4 py-2 font-semibold text-slate-950">Save display name</button></form>{profileMessage&&<p role="status" className="mt-3 text-sm text-teal-200">{profileMessage}</p>}</section></div>}</ProfileContext.Provider>;
 return <main className="flex min-h-screen items-center justify-center p-5"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#151e30] p-7"><h1 className="text-2xl font-bold">Think About It<span className="text-teal-400">.</span></h1><p className="mt-2 text-sm text-slate-400">{mode==='login'?'Sign in to your private workspace':mode==='register'?'Create your private account':'Reset your password'}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode==='register'&&<label className="block text-sm">Display name<input required minLength={3} maxLength={80} autoComplete="nickname" value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 w-full rounded-lg bg-slate-800 p-3" placeholder="How should we call you?"/><span className="mt-1 block text-xs text-slate-400">At least 3 characters. You can change this later in Profile Settings.</span></label>}<label className="block text-sm">Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-lg bg-slate-800 p-3" placeholder="you@example.com"/></label>{mode!=='reset'&&<label className="block text-sm">Password<span className="relative mt-1 block"><input required type={showPassword?"text":"password"} minLength={6} autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-lg bg-slate-800 p-3 pr-12"/><button type="button" aria-label={showPassword?"Hide password":"Show password"} onClick={()=>setShowPassword(v=>!v)} className="absolute right-3 top-3 text-slate-400">{showPassword?<EyeOff size={20}/>:<Eye size={20}/>}</button></span></label>}<button disabled={busy} className="w-full rounded-lg bg-teal-400 p-3 font-semibold text-slate-950 disabled:opacity-50">{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':'Send reset email'}</button></form>{message&&<p role="status" className="mt-4 text-sm text-teal-200">{message}</p>}<div className="mt-6 flex flex-wrap gap-4 text-sm text-slate-400">{mode!=='login'&&<button onClick={()=>{setMode('login');setMessage('')}}>Sign in</button>}{mode!=='register'&&<button onClick={()=>{setMode('register');setMessage('')}}>Create account</button>}{mode!=='reset'&&<button onClick={()=>{setMode('reset');setMessage('')}}>Forgot password?</button>}</div></div></main>;
}
